Infinite scroll for MurrList
Murrengan/murr pull request #105
Opened 2019-06-10 21:44 UTC by Kuzyashin

2019-06-11 09:59 UTC, das-dev requested changes

2019-06-11 09:59 UTC, das-dev commented on static/js/jquery.waypoints.min.js
> +/*!
это для пагинации? Ее же планировали дропнуть с введением подгрузки мурров на скролле, а навигацию осуществлять через фильтры и сортировки. С другой стороны, ни фильтров, ни сортировки в мастере пока нет (часть этой задачи решается). Так что стоит уточнить у Егора, как он хочет видеть муррлист с принятием этого пуллреквеста: с пагинацией или без?
NB! Стоит писать в комменте к пуллреквесту о новых либах/third-party плагинах, которые в нем добавляются: для чего, зачем и почему

2019-06-11 09:59 UTC, das-dev commented on static/js/murr_list.js
> +                $($this).click(function () {
При делегировании тебе нужно повешать один (!) хендлер, а уже внутри него ифать на таргет и исполнять соответсвующий код (метод)

2019-06-11 09:59 UTC, das-dev commented on MurrCard/views.py
> +        page = paginator.page(paginator.num_pages)
предлагаю в шорткаты в кастомный класс вынести эту логику обработки невалидного number: у нас уже есть как минимум два места, где используется пагинация (даже с учетом рефакторинга)

2019-06-11 09:59 UTC, das-dev commented on static/js/murr_list.js
> +                    $murr = $card.closest('.js-murr-card'),
$(event.target), который передается в метод как $card — это ссылка не на карточку мурра, а на то место, куда тыкнули мышкой — поэтому нейминг конфликтует с тем что происходит на самом деле

2019-06-11 09:59 UTC, das-dev commented on static/js/murr_list.js
> -
давай лучше оставим эту пустую строку между фрагментом инициализации состояния метода и всей последующей логикой в его пределах

2019-06-11 09:59 UTC, das-dev commented on templates/MurrCard/includes/_murr_list_card.html
> +<div class="murr-card masonry-item font-black js-murr-card infinite-item" data-murr="{{ murr.slug }}">
не стоит раздувать и без того объемные атрибуты класса. Infinite shortcut, который ты заюзал позволяет задавать свои селекторы как для контейнера. так и для айтемов

2019-06-11 09:59 UTC, das-dev commented on static/js/murr_list.js
> +    }
Мне пока непонятно, почему этот код должен лежать снаружи неймспейса

2019-06-11 10:32 UTC, Kuzyashin commented on static/js/jquery.waypoints.min.js
> +/*!
https://simpleisbetterthancomplex.com/tutorial/2017/03/13/how-to-create-infinite-scroll-with-django.html    

По этому гайду делал

2019-06-11 10:32 UTC, Kuzyashin commented on static/js/jquery.waypoints.min.js
> +/*!
Хотя можно переписать с использованием этого https://infinite-scroll.com/#install

2019-06-11 12:14 UTC, das-dev commented on static/js/jquery.waypoints.min.js
> +/*!
ок.
Допом чекнул гитхаб и доку:
waypoint.js — либа для хендлинга скролла (довольно популярная: 9к звед на гитхабе)
infinite.js — опциональная часть либы, шорткат
т.е. пагинацию с waypoints юзать не обязательно, отключить ее при необходимости не составит большого труда.
но про дроп пагинации (я про часть в интерфейсе) лучше все же спросить

2019-06-11 16:00 UTC, Kuzyashin commented on static/js/jquery.waypoints.min.js
> +/*!
Т.е речь идет о том, убирать вот это или нет?
http://prntscr.com/o0iyha

2019-06-11 17:41 UTC, das-dev commented on static/js/jquery.waypoints.min.js
> +/*!
Да, все верно. Планировалось, что навигация будет осуществляться не с помощью пагинации, а с помощью инфинити скролла, фильтров и сортировки. Т.к. в твоём пулл реквестс добавляется первое, но в мастере пока ещё нет второго, то думаю есть смысл выяснить, оставлять ли пагинацию (с твоего скрина) или уже выпиливать.

2019-06-11 17:41 UTC, das-dev commented on static/js/jquery.waypoints.min.js
> +/*!
Да, все верно. Планировалось, что навигация будет осуществляться не с помощью пагинации, а с помощью инфинити скролла, фильтров и сортировки. Т.к. в твоём пулл реквестс добавляется первое, но в мастере пока ещё нет второго, то думаю есть смысл выяснить, оставлять ли пагинацию (с твоего скрина) или уже выпиливать.

2019-06-11 17:45 UTC, Kuzyashin commented on static/js/jquery.waypoints.min.js
> +/*!
так пагинация(именно кусок на фронте) есть в мастере, а я ее выпиливают и добавляю инфинити скрол.

2019-06-11 17:53 UTC, das-dev commented on static/js/jquery.waypoints.min.js
> +/*!
Нет, это я неправильно понял, для чего изначально тянулась эта либа. Все ок, эту ветку резолвлю

2019-06-11 22:23 UTC, Kuzyashin commented on MurrCard/views.py
> +        page = paginator.page(paginator.num_pages)
Думаю что тут можно переопределить `validate_number` базового пагинатора. Все эксепшены райзит он. Сделать что-то типа такого :     
      
```
class CustomPaginator(Paginator):
    def validate_number(self, number):
        """Validate the given 1-based page number."""
        try:
            if isinstance(number, float) and not number.is_integer():
                raise ValueError
            number = int(number)
        except (TypeError, ValueError):
            return 1
        if number < 1:
            return 1
        if number > self.num_pages:
            if number == 1 and self.allow_empty_first_page:
                pass
            else:
                return self.num_pages
        return number
```

2019-06-12 03:27 UTC, das-dev commented on MurrCard/views.py
> +        page = paginator.page(paginator.num_pages)
Хорошая идея. Но давай максимально переиспользуем уже существующий код.
Накидал навскидку, просто для примера:
```
class MurrenganPaginator(Paginator):
    def validate_number(self, number):
        try:
            number = super(MurrenganPaginator, self).validate_number(number)
        except PageNotAnInteger:
            number = 1
        except EmptyPage:
            number = 1 if number < 1 else self.num_pages
        return number
```

2019-06-12 03:44 UTC, das-dev commented on static/js/murr_list.js
> +                    if ($(event.target).hasClass('js-murr-card-like')) {
не думал, что такая куча else if'ов выйдет. Но другого варианта я пока не вижу

2019-06-12 04:06 UTC, das-dev commented on static/js/murr_list.js
> -                return this.each(function () {
чем мотивировано это изменение?

2019-06-12 04:06 UTC, das-dev commented on static/js/murr_list.js
> +            },
я имел в виду, что нужно прибрать эту конструкцию в метод (что-то типа initInfiniteScroll) и вызывать его на инициализации модуля (метод init). Это же будет так работать?

2019-06-12 04:06 UTC, das-dev commented on static/js/murr_list.js
> +                        else {
коммент был к одному else, но я предполагал что ты их все приведешь к одному виду

2019-06-12 05:40 UTC, das-dev commented on static/js/murr_list.js
> +            },
![image](https://user-images.githubusercontent.com/33005044/59325942-1baf2600-8d0f-11e9-9d90-3a092a5cb641.png)

2019-06-12 09:47 UTC, Kuzyashin commented on static/js/murr_list.js
> -                return this.each(function () {
как я понял,` this.each` проходит при инициализации по всем `murr-card` внутри `murr-list ` . А я хотел уйти от этого и повесить на `murr-list `

2019-06-12 10:37 UTC, Kuzyashin commented on static/js/murr_list.js
> +                        else {
Хм, пропустил(

2019-06-12 10:43 UTC, Kuzyashin commented on MurrCard/views.py
> +        page = paginator.page(paginator.num_pages)
Работает, только 
```
except EmptyPage:
            number = 1 if number < 1 else self.num_pages
```

Завернул `number < 1` в `parse_int`, т.к при передаче `-1` валится на `str<int `

2019-06-13 06:19 UTC, merged