Find by multiple args
Murrengan/murr pull request #108
Opened 2019-06-16 13:48 UTC by asechnaya

2019-06-16 18:53 UTC, Murrengan commented on MurrCard/urls.py
> +    path('find', murr_card.murr_list_find, name='murr_list_find'),
why 'find' not 'find/' in pathname?

2019-06-17 13:37 UTC, das-dev commented on MurrCard/views.py
> +        query &= Q(author__username__in=authors)
А обычный `.filter` здесь не подойдет?

2019-07-22 10:52 UTC, Kuzyashin requested changes

2019-07-22 10:52 UTC, Kuzyashin commented on MurrCard/views.py
> +    murrs = Murr.objects.all()
надо отфильтровать муры с жалобами, по аналогии с #123

2019-07-30 10:39 UTC, merged