horizontal murr_list fix
Murrengan/murr pull request #114
Opened 2019-06-22 11:01 UTC by wm2

распределил новости горизонтально

2019-06-22 18:02 UTC, das-dev reviewed
Код на локале пока не тестил

2019-06-22 18:02 UTC, das-dev commented on static/css/murr_list.css
> +  grid-auto-rows: 0; /* [3] Set the height for implicitly-created row track */
для базовых .masonry стилей есть отдельный файл

2019-06-22 18:02 UTC, das-dev commented on static/css/murr_list.css
> +  grid-gap: 1em; /* [1] Add some gap between rows and columns */
этот комментарий не нужен - ничего нового он не сообщает

2019-06-22 18:28 UTC, Kuzyashin commented on static/css/murr_list.css
> +  grid-gap: 1em; /* [1] Add some gap between rows and columns */
https://w3bits.com/css-grid-masonry/ - вот тут вроде как код с комментами

2019-06-22 19:08 UTC, das-dev commented on static/js/masonry_grid.js
> +  var rowSpan = Math.ceil((item.querySelector('.masonry-content').getBoundingClientRect().height+rowGap)/(rowHeight+rowGap) + 4);
вот эту строку хорошо бы укоротить: разбей ее на на две переменных, например

2019-06-22 19:11 UTC, das-dev commented on static/css/murr_list.css
> +  grid-gap: 1em; /* [1] Add some gap between rows and columns */
Вот, лучше уж тогда ссылку на эту статью добавить в комменты

2019-06-23 08:33 UTC, Kuzyashin requested changes
У меня некорректно ресайзятся мурры, и на сафари и на хроме.  
http://prntscr.com/o5icqb
http://prntscr.com/o5ictw

2019-06-25 18:14 UTC, Murrengan approved these changes

2019-06-25 18:14 UTC, merged