[+] Profile small improvements
Murrengan/murr pull request #92
Opened 2019-06-05 15:13 UTC by dipperside

2019-06-06 07:24 UTC, das-dev requested changes

2019-06-06 07:24 UTC, das-dev commented on Murren/forms.py
>                                             'viewport': {
между аргументами забыл пробел. Но еще лучше для читаемости было бы перенести `label=""` на новую строку, между required и widget: так соседние параметры будут на одном уровне визуально — такое легче парсить глазами. А еще лучше объявление лейблов унести в мету (т.к. это ModelForm). И виджеты тоже.
Вот как это выглядит в [доке](https://docs.djangoproject.com/en/2.2/topics/forms/modelforms/):
```
from django.utils.translation import gettext_lazy as _

class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ('name', 'title', 'birth_date')
        labels = {
            'name': _('Writer'),
        }
        help_texts = {
            'name': _('Some useful help text.'),
        }
        error_messages = {
            'name': {
                'max_length': _("This writer's name is too long."),
            },
        }
```

2019-06-06 07:24 UTC, das-dev commented on Murren/forms.py
> +                            label="Почта")
Может для лейблов использовать каноничные Логин и Email?

2019-06-06 07:24 UTC, das-dev commented on templates/Murren/murren_edit.html
> +                            {% if field.label %}
лейбл все-таки должен быть лейблом а не спаном

2019-06-06 07:24 UTC, das-dev commented on templates/Murren/murren_edit.html
> +                            {% if field.label %}
и проще наверно было бы заюзать {{ field.label_tag }} вместо `<span class="input-label_text text-muted">{{ field.label }}:</span>`

2019-06-06 07:24 UTC, das-dev commented on static/css/base.css
> +.button_float-position_right {
я бы предпочел `.button_float_right`, как более лаконичное и при этом вроде вполне понятное. Но это чисто субъективно

2019-06-06 07:46 UTC, dipperside commented on Murren/forms.py
> +                            label="Почта")
Значит плейсхолдер тоже изменить

2019-06-06 07:48 UTC, dipperside commented on Murren/forms.py
>                                             'viewport': {
**_Ок. Согласен._**

2019-06-07 17:33 UTC, dipperside commented on Murren/forms.py
>                                             'viewport': {
Блок с CroppieField исправил, но оставил все же в классе, так как не уверен в переносе в Мета блок

2019-06-07 20:50 UTC, Kuzyashin commented on Murren/forms.py
> +    profile_picture = CroppieField(required=False,
Вот если превратить `profile_picture = CroppieField(required=False,` в    
```
    CroppieField(
        required=False,
```
 то вообще четко будет

2019-06-09 04:38 UTC, merged